### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/gpustat-feedstock#4]
I know the package is noarch, but blessings is not available on windows - it appears that package is not maintained very actively [anymore](https://github.com/erikrose/blessings/issues/160), but there is a fork that works (and is in conda-forge already): https://github.com/jquast/blessed

As a matter of fact, upstream `gpustst` [switched](https://github.com/wookayin/gpustat/pull/78) to this already, but there has been no release since then.

**Comment by mattip** [comment]
There was a 1.0.0 release which supports windows.
